# filtered, see .gitattributes
SET(VERSION_MAJOR "5")
SET(VERSION_MINOR "15")
SET(VERSION_PATCH "200")
SET(VERSION_DATE "2026-09-28")
SET(VERSION_GIT_DATE %git_date%)
SET(VERSION_GIT_STAMP %git_stamp%)
